# To use:
#
# mkdir solr-cluster
# cd solr-cluster
# docker-compose up

version: '3'
services:
  solr1:
    image: solr:8.5.1
    container_name: solr1
    ports:
     - "8982:8983"
    environment:
      - ZK_HOST=zoo1:2181
    networks:
      - solr
    depends_on:
      - zoo1

  solr2:
    image: solr:8.5.1
    container_name: solr2
    ports:
     - "8983:8983"
    environment:
      - ZK_HOST=zoo1:2181
    networks:
      - solr
    depends_on:
      - zoo1

  zoo1:
    image: zookeeper:3.5
    container_name: zoo1
    restart: always
    hostname: zoo1
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181
    networks:
      - solr

  jupyter:
    image: jupyter/all-spark-notebook
    container_name: jupyter
    ports:
     - "8888:8888"
    networks:
      - solr
    command: ["jupyter", "notebook", "--ip='*'", "--NotebookApp.token=''", "--NotebookApp.password=''"]
    volumes:
      - "./work:/home/jovyan/work"

networks:
  solr:
